### ISSUE TITLE
typed array may be a view to a slice with-in the buffer

### ISSUE THREAD

**Issue by Gozala** [mikeal/bytesish#1]
It seems that code here assumes that [`byteOffset`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteOffset) is going to be `0` and [`byteLength`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteLength) will match `length`:

https://github.com/mikeal/bytesish/blob/0e56d2ad196d0f64c19248d455d46e439530f465/browser.js#L18-L20

However it may not necessarily be true, e.g:

```js
const buffer = new ArrayBuffer(64)
const bytes = new Uint8Array(buffer, 5, 10)
buffer.length // 64
bytes.byteOffest // 5
bytes.length // 10
```

**Comment by mikeal** [comment]
fixed in latest push.
