### ISSUE TITLE
I think you may want to use DataView instead of ArrayBuffer

### ISSUE THREAD

**Issue by Gozala** [mikeal/bytesish#2]
[Twitter thread](https://twitter.com/mikeal/status/1150856074481688576) got little too long to be useful so following up here instead.

From what I understand primary goals are to achieve zero copying while without commitment to specific format. In that case I think [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) might be a most adequate choice as it still can represent a view of the slice within the `ArrayBuffer` and has get / set methods for arbitrary format.

It should also enable remove the need to copy memory from node `Buffer` even if it represents a slice.

**Comment by mikeal** [comment]
haha, we wrote this up at the exact same time :) https://github.com/mikeal/bytesish/issues/3

closing as duplicate :)
