### ISSUE TITLE
Alternative approach: normalize to DataView

### ISSUE THREAD

**Issue by mikeal** [mikeal/bytesish#3]
An alternative approach that could get this library down to *zero* copies is to normalize everything to a [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView).

We’d need to add a method `bytesish.arrayBuffer(_from)` to do an arrayBuffer conversion similar to what we do now because there are still cases that you need a discreet ArrayBuffer (apparently you can’t passed views across threads).

We’d also need to add a lot of methods that DataView is missing (slice, indexOf, etc).

**Comment by Gozala** [comment]
> We’d also need to add a lot of methods that `DataView` is missing (slice, indexOf, etc).

The reason those methods do not exist is because `DataView` is agnostic of format. Meaning buffer maybe encoding things in Uint32 or Uint8 or both. So depending on what you consider format to be those will have to do a different things.

**Comment by mikeal** [comment]
> The reason those methods do not exist is because DataView is agnostic of format. Meaning buffer maybe encoding things in Uint32 or Uint8 or both. So depending on what you consider format to be those will have to do a different things.

That makes sense when working with encodings but what these do in Node.js `Buffer` is just accept byte offsets and return a new view, and `ArrayBuffer` slice() does the same except it copies. 

I think that we’d want a method called `slice()` that takes byte offsets and returns a new DataView, and a method called `copy()` that returns a copy of the ArrayBuffer with a new DataView on it.

**Comment by mikeal** [comment]
@Gozala do you know offhand if there are API’s that accept TypeArray’s but **do not** accept DataView?

**Comment by Gozala** [comment]
> @Gozala do you know offhand if there are API’s that accept TypeArray’s but **do not** accept DataView?

I think most web APIs take arbitrary typed array but I'm not confident.

**Comment by mikeal** [comment]
`DataView` doesn’t *appear* to be a subclass of TypedArray and doesn’t include most of the methods you find on a TypedArray *but* `ArrayBuffer.isView(new DataView(new ArrayBuffer())) === true` so I’m not sure what to think.

**Comment by Gozala** [comment]
I think it might be worth rolling out your own canonical representation based on `DataView`:

```js
class Bytes extends DataView {
  static fromTypedArray(typedArray) {
    return new Bytes(typedArray.buffer, typedArray.byteOffset, typedArray.byteLength)
  }
  slice(start, end) {
     return new Bytes(this.buffer, this.byteOffset, end - start)
  }
}

const bytes = Bytes.fromTypedArray(new TextEncoder().encode('hello world'))

new TextDecoder().decode(bytes.slice(0, 5)) // hello
```

**Comment by mikeal** [comment]
Perhaps the thing to do is:

* normalize to `DataView`. `bytesish(anything)` returns a `DataView`.
* but `bytesish.native(anything)` returns a `UInt8Array` in the Browser and `Buffer` in Node.js

This way, people working with binary get `DataView` but can then easily return a more usable type from their functions that we know work everywhere.

**Comment by mikeal** [comment]
@Gozala early unpublished versions of this module had a new class in them called `Bytes` and I ended up backing away from that toward this more functional approach because I was concerned that people would end up passing around this new type instead of converting back to better native types, that’s why i settled on this more functional approach.

**Comment by mikeal** [comment]
> `new TextDecoder().decode(bytes.slice(0, 5)) // hello`

One of the reasons I wrote the string conversion stuff into `bytesish` is because TextEncoder/TextDecoder aren’t available in Node.js :(

**Comment by Gozala** [comment]
> @Gozala early unpublished versions of this module had a new class in them called `Bytes` and I ended up backing away from that toward this more functional approach because I was concerned that people would end up passing around this new type instead of converting back to better native types, that’s why i settled on this more functional approach.

Yes that is a good point, introducing third class along the ones we already have is not going to make things easier :)

**Comment by Gozala** [comment]
For what it's worth I think node `Buffer` is mostly equivalent of  `Uint8Array` but comes with bunch of extra methods to do string encoding / decoding. Which is why I initially suggested to use `Uint8Array` instead.
